updated the plots that didn't work
ClimateMatchAcademy/course-content pull request #230
Opened 2023-07-20 16:55 UTC by OhadZivan

fixed the students questions to match the TA ones

2023-07-20 19:46 UTC, jlpearso commented
@WesleyTheGeolien were these changes that @OhadZivan made due to the formatter? Also @OhadZivan we will be generating the student notebooks from the root tutorials, we just have not done this day yet. So as long as the root files are modified we will have updated student books.

2023-07-25 11:03 UTC, WesleyTheGeolien requested changes

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> -    "df = df_tmp\n"
I think this is needed to use df_tmp else df is overwritten in the exercice cells / student bit so the df / df_tmp mechanism needs to stay

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "fig,ax=plt.subplots(figsize=(20,5))\n",
please reset formatting

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> -    "selected_words_2 = [..., ..., ..., ..., ...]\n",
I think this needs to stay as is else it is not possible to iterate over `selected_words_2` in the next line

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> -    "selected_tweet_fraction_2 = ...\n",
white space is important I think

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "afinn_wl_df = pd.read_csv(pooch_load(url_afinn_wl,filename_afinn_wl),\n",
please reset formatting

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "fig,ax=plt.subplots()\n",
whitespace improtant

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "ax.set_ylabel('dictionary counts')"
formatting important

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "    ax.axvline(0,color=[0.7]*3,zorder=1)\n",
formatting important

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "    fig,ax=plt.subplots(figsize=(10,5))\n",
whitespaces needed

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "    print(wc)\n",
please remove print statement

2023-07-25 11:03 UTC, WesleyTheGeolien commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
> +    "    ax_wc = ax.inset_axes([0.2,0.2,0.6,0.6])\n",
is this reflected in the student exercice bit?

2023-07-25 12:35 UTC, WesleyTheGeolien commented
fixed in #245

2023-07-25 12:35 UTC, closed without merging